Controllers/LoginController.cs
using System;
using EspacioInterfaces;
using EspacioViewModels;
using Microsoft.AspNetCore.Mvc;


public class LoginController : Controller
{
    private readonly IAuthenticationService _authenticationService;

    public LoginController(IAuthenticationService authenticationService)
    {
        _authenticationService = authenticationService;
    }

    public IActionResult Index()
    {
        var vm = new LoginViewModel
        {
            IsAuthenticated = HttpContext.Session.GetString("IsAuthenticated") == "true"
        };
        return View(vm);
    }

    [HttpPost]
    public IActionResult Login(LoginViewModel vm)
    {

        if (string.IsNullOrEmpty(vm.Username) || string.IsNullOrEmpty(vm.Pass))
        {
            vm.ErrorMessage = "Debe ingresar usuario y contraseña.";
            return View("Index", vm);
        }

        if (_authenticationService.Login(vm.Username, vm.Pass))
        {
            return RedirectToAction("Index", "Home");
        }

        vm.ErrorMessage = "Credenciales inválidas.";
        vm.IsAuthenticated = false;
        return View("Index", vm);
    }

     public IActionResult Logout()
    {
        // Limpiar la sesión
        HttpContext.Session.Clear();

        // Redirigir a la vista de login
        return RedirectToAction("Index");
    }
}

Controllers/PresupuestoController.cs
using System.Diagnostics;
using EspacioInterfaces;
using EspacioPresupuesto;
using EspacioProducto;
using EspacioRepositories;
using EspacioViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using tl2_tp8_2025_marta16g.Models;

namespace tl2_tp8_2025_marta16g.Controllers;

public class PresupuestoController : Controller
{
    private IPresupuestoRepository presupuestoRepository;
    private IProductoRepository productoRepository;
    private IAuthenticationService _authService;

    public PresupuestoController(IPresupuestoRepository presurepo, IProductoRepository prodRepo, IAuthenticationService authService)
    {
        presupuestoRepository = presurepo;
        productoRepository = prodRepo;
        _authService = authService;
    }

    public IActionResult Index()
    {
        if (!_authService.IsAuthenticated())
        {
            return RedirectToAction("Index", "Login");
        }

        if (_authService.HasAccessLevel("Administrador") ||
_authService.HasAccessLevel("Cliente"))
        {
            //si es es valido entra sino vuelve a login
            var presupuestos = presupuestoRepository.GetAll();
            return View(presupuestos);
        }
        else
        {
            return RedirectToAction("Index", "Login");
        }
    }

    [HttpGet]
    public IActionResult Detalle(int idPresupuesto)
    {
        Presupuesto miPresupuesto = presupuestoRepository.GetById(idPresupuesto);
        return View(miPresupuesto);
    }

    [HttpPost]
    public IActionResult AgregarDetalle(int idPresupuesto, int idProducto, int cantidad)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null)
        {
            return securityCheck;
        }
        presupuestoRepository.AgregarDetalle(idPresupuesto, idProducto, cantidad);

        return RedirectToAction("Detalle", new { idPresupuesto });
    }


    [HttpGet]
    public IActionResult Editar(int idPresupuesto)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null)
        {
            return securityCheck;
        }
        Presupuesto presupuesto = presupuestoRepository.GetById(idPresupuesto);
        return View(presupuesto);
    }

    [HttpPost]
    public IActionResult Editar(Presupuesto presupuesto)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null)
        {
            return securityCheck;
        }
        presupuestoRepository.Update(presupuesto.IdPresupuesto, presupuesto);

        return RedirectToAction(nameof(Index));
    }


    [HttpGet]
    public IActionResult Eliminar(int idPresupuesto)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null)
        {
            return securityCheck;
        }
        Presupuesto presupuesto = presupuestoRepository.GetById(idPresupuesto);
        return View(presupuesto);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult EliminarConfirmado(int idPresupuesto)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null)
        {
            return securityCheck;
        }
        bool exito;
        exito = presupuestoRepository.Delete(idPresupuesto);
        if (exito)
        {
            return RedirectToAction(nameof(Index));
        }
        else
        {
            return Error();
        }
    }

    [HttpGet]
    public IActionResult AgregarProducto(int idPresupuesto)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null)
        {
            return securityCheck;
        }
        List<Producto> productos = productoRepository.GetAll();

        AgregarProductoViewModel vm = new AgregarProductoViewModel { IdPresupuesto = idPresupuesto, ListaProductos = new SelectList(productos, "IdProducto", "Descripcion") };

        return View(vm);
    }


    [HttpPost]
    public IActionResult AgregarProducto(AgregarProductoViewModel vm)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null)
        {
            return securityCheck;
        }

        if (!ModelState.IsValid)
        {
            var productos = productoRepository.GetAll();
            vm.ListaProductos = new SelectList(productos, "IdProducto", "Descripcion");
            return View(vm);
        }

        presupuestoRepository.AgregarDetalle(vm.IdPresupuesto, vm.IdProducto, vm.Cantidad);

        return RedirectToAction(nameof(Detalle), new { idPresupuesto = vm.IdPresupuesto });
    }


    public IActionResult EliminarDetalle(int idPresupuesto, int idProducto)
    {
        presupuestoRepository.EliminarDetalle(idPresupuesto, idProducto);

        return RedirectToAction("Detalle", new { idPresupuesto = idPresupuesto });
    }

    public IActionResult AccesoDenegado()
    {
        return View();
    }

    private IActionResult CheckAdminPermissions()
    {
        // 1. No logueado? -> vuelve al login
        if (!_authService.IsAuthenticated())
        {
            return RedirectToAction("Index", "Login");
        }

        // 2. No es Administrador? -> Da Error
        if (!_authService.HasAccessLevel("Administrador"))
        {
            // Llamamos a AccesoDenegado (llama a la vista correspondiente de Productos)
            return RedirectToAction(nameof(AccesoDenegado));
        }
        return null; // Permiso concedido
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }


}

Controllers/ProductoController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp8_2025_marta16g.Models;
using EspacioRepositories;
using EspacioProducto;
using EspacioViewModels;
using EspacioInterfaces;

namespace tl2_tp8_2025_marta16g.Controllers;

public class ProductoController : Controller
{
    private IProductoRepository productoRepository;
    private IAuthenticationService _authService;
    public ProductoController(IProductoRepository prodRepo,
IAuthenticationService authService)
    {
        // productoRepository = new ProductoRepository();
        productoRepository = prodRepo;
        _authService = authService;
    }

    public IActionResult Index()
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null)
        {
            return securityCheck;
        }

        List<Producto> listaDeProductos = productoRepository.GetAll();
        return View(listaDeProductos);
    }

    [HttpGet]
    public IActionResult Crear()
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;
        return View();
    }

    [HttpPost]
    public IActionResult Crear(ProductoViewModel vm)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;
        if (!ModelState.IsValid)
        {
            return View(vm);
        }

        Producto nuevoProducto = new Producto { Descripcion = vm.Descripcion, Precio = vm.Precio };

        productoRepository.Create(nuevoProducto);

        return RedirectToAction("Index");
    }


    [HttpGet]
    public IActionResult Editar(int idProducto)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;
        Producto producto = productoRepository.GetById(idProducto);

        ProductoViewModel nuevoVm = new ProductoViewModel { IdProducto = producto.IdProducto, Descripcion = producto.Descripcion, Precio = producto.Precio };

        return View(nuevoVm);
    }


    [HttpPost]
    public IActionResult Editar(ProductoViewModel vm)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;
        if (!ModelState.IsValid)
        {
            return View(vm);
        }

        Producto productoEditado = new Producto { IdProducto = vm.IdProducto, Descripcion = vm.Descripcion, Precio = vm.Precio };

        productoRepository.Update(productoEditado.IdProducto, productoEditado);

        return RedirectToAction(nameof(Index));
    }

    [HttpGet]
    public IActionResult Eliminar(int idProducto)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;
        Producto producto = productoRepository.GetById(idProducto);
        return View(producto);
    }

    [HttpPost, ActionName("Delete")]
    public IActionResult EliminarConfirmado(int idProducto)
    {
        var securityCheck = CheckAdminPermissions();
        if (securityCheck != null) return securityCheck;
        bool exito;
        exito = productoRepository.Delete(idProducto);
        if (exito)
        {
            return RedirectToAction(nameof(Index));
        }
        else
        {
            return Error();
        }
    }

    public IActionResult AccesoDenegado()
    {
        return View();
    }

    private IActionResult CheckAdminPermissions()
    {
        // 1. No logueado? -> vuelve al login
        if (!_authService.IsAuthenticated())
        {
            return RedirectToAction("Index", "Login");
        }

        // 2. No es Administrador? -> Da Error
        if (!_authService.HasAccessLevel("Administrador"))
        {
            // Llamamos a AccesoDenegado (llama a la vista correspondiente de Productos)
            return RedirectToAction(nameof(AccesoDenegado));
        }
        return null; // Permiso concedido
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    var isAuthenticated = false;
    var username = string.Empty;

    if (HttpContextAccessor.HttpContext.Session.GetString("IsAuthenticated") == "true")
    {
        isAuthenticated = true;
        username = HttpContextAccessor.HttpContext.Session.GetString("User");
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tl2_tp8_2025_marta16g</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tl2_tp8_2025_marta16g.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trabajo Práctico N°8</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Presupuesto" asp-action="Index">Presupuesto</a>
                        </li>
                        @if (isAuthenticated)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-dark me-3">Bienvenido, @username</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Logout", "Login")">Cerrar sesión</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Login")">Iniciar sesión</a>
                            </li>
                        }
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - tl2_tp8_2025_marta16g - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>